version: "3.9"

services:
  php8:
    extra_hosts:
    - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile_php8cli
      #args:
      #  pathapp: ./php_app
    entrypoint: ["php", "-S", "0.0.0.0:8081"]
    volumes:
      - ./php_app1/:/app/
    ports:
      - "8080:8081"
